# Generated by Django 5.1.15 on 2026-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOARDING_REMINDER', 'Boarding Reminder'), ('VACCINATION_EXPIRY', 'Vaccination Expiry'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('INVOICE_GENERATION', 'Invoice Generated'), ('CHECK_IN_REMINDER', 'Check-In Alert'), ('CHECK_OUT_REMINDER', 'Check-Out Alert'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
