# Generated by Django 5.1.15 on 2026-09-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('boarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='boarding_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='boarding.boardingbooking'),
        ),
    ]
