# Generated by Django 5.1.15 on 2026-09-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], default='DOG', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('microchip_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('photo', models.URLField(blank=True, default='', max_length=500)),
                ('blood_group', models.CharField(blank=True, max_length=20)),
                ('allergies', models.TextField(blank=True, help_text='Known pet allergies')),
                ('medical_conditions', models.TextField(blank=True, help_text='Pre-existing medical conditions')),
                ('special_needs', models.TextField(blank=True, help_text='Physical or behavioral special care needs')),
                ('dietary_preferences', models.TextField(blank=True, help_text='Brand, wet/dry, timing, quantity')),
                ('personality_behavior', models.TextField(blank=True, help_text='Playful, anxious, dog-friendly, etc.')),
                ('emergency_instructions', models.TextField(blank=True, help_text='In case of medical distress')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DECEASED', 'Deceased'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='customers.customer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
