# Generated by Django 5.1.15 on 2026-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('BOARDING', 'Pet Boarding'), ('DAYCARE', 'Doggy Daycare'), ('GROOMING', 'Pet Grooming'), ('TRAINING', 'Pet Training'), ('VETERINARY', 'Veterinary Checkup'), ('BATHING', 'Bathing & Spa'), ('NAIL_TRIMMING', 'Nail Trimming'), ('TRANSPORTATION', 'Pet Taxi / Transport'), ('OTHER', 'Other Service')], default='GROOMING', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
