# Generated by Django 5.1.15 on 2026-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('package', models.CharField(choices=[('STANDARD', 'Standard Package'), ('PREMIUM', 'Premium Package'), ('LUXURY', 'Luxury VIP Package'), ('DAYCARE', 'Daycare Only')], default='STANDARD', max_length=20)),
                ('check_in_date', models.DateField(db_index=True)),
                ('expected_check_out_date', models.DateField(db_index=True)),
                ('actual_check_out_date', models.DateField(blank=True, null=True)),
                ('feeding_instructions', models.TextField(blank=True)),
                ('medication_instructions', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], db_index=True, default='RESERVED', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='BoardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_vaccination_verified', models.BooleanField(default=False)),
                ('checkin_health_condition_checked', models.BooleanField(default=False)),
                ('checkin_weight_recorded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('checkin_belongings_received', models.BooleanField(default=False)),
                ('checkin_belongings_notes', models.TextField(blank=True)),
                ('checkin_feeding_recorded', models.BooleanField(default=False)),
                ('checkin_medication_recorded', models.BooleanField(default=False)),
                ('checkin_emergency_verified', models.BooleanField(default=False)),
                ('checkin_owner_instructions', models.BooleanField(default=False)),
                ('checkin_payment_checked', models.BooleanField(default=False)),
                ('checkin_completed', models.BooleanField(default=False)),
                ('checkin_completed_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_condition_checked', models.BooleanField(default=False)),
                ('checkout_belongings_returned', models.BooleanField(default=False)),
                ('checkout_medication_completed', models.BooleanField(default=False)),
                ('checkout_final_services_verified', models.BooleanField(default=False)),
                ('checkout_invoice_generated', models.BooleanField(default=False)),
                ('checkout_payment_completed', models.BooleanField(default=False)),
                ('checkout_owner_confirmation', models.BooleanField(default=False)),
                ('checkout_completed', models.BooleanField(default=False)),
                ('checkout_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('FEEDING', 'Feeding'), ('MEDICATION', 'Medication Administered'), ('EXERCISE', 'Exercise / Playtime'), ('GROOMING', 'Grooming / Brushing'), ('POTTY', 'Potty Break'), ('BEHAVIOR', 'Behavior Observation'), ('HEALTH_CHECK', 'Health Check')], default='FEEDING', max_length=30)),
                ('notes', models.TextField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('STANDARD', 'Standard Suite'), ('PREMIUM', 'Premium Suite'), ('LUXURY', 'Luxury Penthouse'), ('DAYCARE', 'Daycare Playpen')], default='STANDARD', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=35.0, max_digits=8)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance / Cleaning')], default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
    ]
