# Generated by Django 5.1.15 on 2026-09-08 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boarding', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingchecklist',
            name='checkin_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardingchecklist',
            name='checkout_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='boarding.boardingbooking'),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardingbooking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='boarding.room'),
        ),
    ]
