# Generated by Django 5.1.15 on 2026-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingbooking',
            name='check_in_time',
            field=models.TimeField(blank=True, default='09:00', null=True),
        ),
        migrations.AddField(
            model_name='boardingbooking',
            name='check_out_time',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
    ]
