# Generated by Django 5.1.15 on 2026-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0004_boardingbooking_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingbooking',
            name='stay_photo',
            field=models.TextField(blank=True, default='', help_text='Latest live photo of pet during boarding stay'),
        ),
        migrations.AddField(
            model_name='boardingbooking',
            name='stay_photo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
