# Generated by Django 5.1.15 on 2026-09-25 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0005_boardingbooking_stay_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycarelog',
            options={'ordering': ['activity_time', 'logged_at']},
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='activity_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='activity_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='belongings_notes',
            field=models.TextField(blank=True, help_text='Belongings received at arrival or returned at departure'),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='dietary_notes',
            field=models.TextField(blank=True, help_text='Food intake or appetite level'),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='health_notes',
            field=models.TextField(blank=True, help_text='Health, coat, or vital observations'),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='mood',
            field=models.CharField(blank=True, choices=[('HAPPY', 'Happy & Wagging'), ('PLAYFUL', 'Playful & Energetic'), ('CALM', 'Calm & Relaxed'), ('AFFECTIONATE', 'Cuddly & Affectionate'), ('SHY', 'Shy / Needs Reassurance'), ('ANXIOUS', 'Anxious / Settling In'), ('SLEEPY', 'Sleepy & Resting')], default='HAPPY', max_length=20),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='photo',
            field=models.TextField(blank=True, default='', help_text='Activity photo (URL or base64)'),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='stage',
            field=models.CharField(choices=[('ARRIVAL', 'Arrival & Intake (When Pet Came)'), ('DAILY', 'Daily Stay Activity'), ('DEPARTURE', 'Departure & Farewell (When Pet Leaves)')], db_index=True, default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailycarelog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailycarelog',
            name='care_type',
            field=models.CharField(choices=[('ARRIVAL', 'Arrival & Intake'), ('DEPARTURE', 'Departure & Check-Out'), ('FEEDING', 'Feeding & Treats'), ('MEDICATION', 'Medication Administered'), ('EXERCISE', 'Exercise & Playtime'), ('WALK', 'Outdoor Walk & Stroll'), ('GROOMING', 'Grooming & Bathing'), ('NAP', 'Nap & Rest Time'), ('POTTY', 'Potty Break'), ('BEHAVIOR', 'Behavior & Mood Check'), ('HEALTH_CHECK', 'Health & Vital Check'), ('PHOTO', 'Photo Moment')], default='FEEDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailycarelog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_care_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
