# Generated by Django 5.1.15 on 2026-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fed_at', models.DateTimeField(auto_now_add=True)),
                ('amount_eaten', models.CharField(default='All', help_text='e.g. All, Half, None', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-fed_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(help_text='e.g. Royal Canin Adult Dry Kibble', max_length=150)),
                ('quantity', models.CharField(help_text='e.g. 1 cup (200g)', max_length=100)),
                ('feeding_time', models.CharField(help_text='e.g. 08:00 AM & 06:00 PM', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. Twice a day', max_length=100)),
                ('special_instructions', models.TextField(blank=True, help_text='e.g. Add warm water, separate from other dogs')),
                ('last_fed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pet', 'feeding_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(db_index=True)),
                ('veterinarian', models.CharField(max_length=150)),
                ('diagnosis', models.CharField(max_length=255)),
                ('symptoms', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('document_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(help_text='e.g. 1 tablet, 5ml, 2 drops', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. Twice daily, Every 8 hours', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions e.g. with food')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-status', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-administered_at'],
            },
        ),
    ]
