# Generated by Django 5.1.15 on 2026-09-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(db_index=True, max_length=150)),
                ('vaccination_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('veterinarian', models.CharField(blank=True, max_length=150)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('document_url', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
